apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-demoweb
  name: go-demoweb
  namespace: gitops-demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-demoweb
status:
  loadBalancer: {}
